### ISSUE TITLE
Publish live version on GH pages

### ISSUE THREAD

**Issue by rubensworks** [SolidLabResearch/solid-todo-app-vue#1]
Like in Vidya's app, we should always have the latest version of the app live on GH pages.

**Comment by surilindur** [comment]
Publishing works now, but the build for production breaks something and the published version does not work. Running locally works, so there is something wrong with the build process/tooling. I am investigating how to fix it.

**Comment by surilindur** [comment]
The live version should now work, and I have added the link to the readme.
