### ISSUE TITLE
Error handling on invalid states

### ISSUE THREAD

**Issue by rubensworks** [SolidLabResearch/solid-todo-app-vue#5]
We should make sure that nice error dialogs are shown when something goes wrong.
For example, when no OIDC issuer was found in the profile.

**Comment by surilindur** [comment]
There is now an error popup (red) displayed for when an error occurs in the logic, and a confirmation (green) when an operation completes successfully, so I would imagine this is fixed. There should not be any errors left that are not displayed to the user, unless it is something about the frameworks that breaks and cannot be caught, I think.
